### ISSUE TITLE
Teatime is dead

### ISSUE THREAD

**Issue by attaboy** [attaboy/isitteatimeyet#5]
RIP Teatime

**Comment by azymnis** [comment]
RIP indeed

**Comment by nielsvaneck** [comment]
: (

**Comment by miguelrios** [comment]
Teatime is back!

**Comment by attaboy** [comment]
Just fixed with new teatime time. Still thinks teatime is every Friday though.

**Comment by esbie** [comment]
closing this issue as won't fix

**Comment by attaboy** [comment]
I let the domain name expire. 😶
